name: Frontend_CI

on:
  push:
    paths:
      - 'frontend/**'
  pull_request:
    paths:
      - 'frontend/**'
  workflow_dispatch:

jobs:
  call-common:
    uses: ./.github/workflows/common-ci.yml
    with:
      working_directory: frontend
      image_name: frontend
      dockerfile_path: frontend/
      build_context: frontend
      run_build: true
      sonar_project_key: frontend   # ✅ unique key

    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}